name: Build and Deploy

on:
  push:
    branches:
      - Development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'  # Ensure you use a version compatible with your project

      - name: Publish .NET Core Project
        run: dotnet publish BlazorApp.csproj -c Release -o release --nologo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: release/wwwroot
